name: Conditional PR Flow

on:
  pull_request:
    branches:
      - main

jobs:
  check-up-to-date:
    name: Check branch is up to date with main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Check main sha
        run: |
          git fetch origin main
          if ! git merge-base --is-ancestor origin/main HEAD; then
            echo "Branch is out of date with main"
          fi
          echo "Branch is in date with main"

      - name: Check submodule shas
        run: |
          for submodulePath in remoteSub; do
            echo "Processing $submodulePath"
            SHA_A=$(git rev-parse HEAD:remoteSub)
            SHA_B=$(git rev-parse origin/main:remoteSub)
            echo "SHA_A is $SHA_A and SHA_B is $SHA_B"
          

  echo-hello-world:
    name: Echo Hello World
    runs-on: ubuntu-latest
    needs: check-up-to-date
    steps:
      - name: Echo hello world
        run: echo "hello world"
