name: Conditional PR Flow

on:
  pull_request:
    branches:
      - main

jobs:
  check-up-to-date:
    name: Check branch is up to date with main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Check shas of repository and submodules
        run: |
          git fetch origin main
          if [ ! git merge-base --is-ancestor origin/main HEAD ]; then
              echo "Branch is out of date with main"
          else
              echo "Branch is in date with main"
          fi

          for submodulePath in remoteSub; do
              echo "Processing $submodulePath"
              SHA_A=$(git rev-parse HEAD:remoteSub)
              SHA_B=$(git rev-parse origin/main:remoteSub)
              if [ "$SHA_A" = "$SHA_B" ]; then
                  echo "SHAs for $submodulePath are equal"
                  continue
              fi
              echo "SHAs for $submodulePath differ"
              if [ ! -d "$submodulePath" ]; then
                  echo "Folder $submodulePath not found"
                  exit 1
              fi
              (
                  cd $submodulePath
                  git fetch origin
                  if ! git merge-base --is-ancestor $SHA_B $SHA_A; then
                      echo "submodule $submodulePath is out of date with main"
                  else
                      echo "submodule $submodulePath is in date with main"
                  fi
              )
          done
          

  echo-hello-world:
    name: Echo Hello World
    runs-on: ubuntu-latest
    needs: check-up-to-date
    steps:
      - name: Echo hello world
        run: echo "hello world"
